# Generated by Django 4.2.11 on 2024-07-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('first_topic', models.CharField(max_length=100)),
                ('second_topic', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_Data_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Father_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Mother_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Total_family_mamber', models.CharField(blank=True, max_length=10, null=True)),
                ('Data_of_birth', models.CharField(blank=True, max_length=10, null=True)),
                ('Nid_card_number', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='HomePage/media')),
            ],
        ),
    ]
