# Generated by Django 4.2.11 on 2024-07-09 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
    ]
